services:
    app:
        image: ghcr.io/rzb-it/eventually:latest
        build:
            dockerfile: ci/eventually/Dockerfile
            context: .
            ssh:
             - default
        container_name: eventually
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=db
        ports:
            - "8080:8080"
        volumes:
            - ./:/app:ro

    db:
        image: postgres:latest
        env_file:
            - .env
        ports:
          - "5432:5432"
        volumes:
            - ./.local/postgres/data:/var/lib/postgresql/data
