version: 1
disable_existing_loggers: False
formatters:
  default:
    # "()": "json_log_formatter.VerboseJSONFormatter"
    "()": "logging.Formatter"
    format: '[%(levelname)s/%(name)s] %(asctime)s %(message)s'
    datefmt: '%d.%m.%Y %H:%M:%S'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: ERROR
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - default
    propagate: no
  sqlalchemy.engine.Engine:
    level: ERROR
    handlers:
      - default
    propagate: no

root:
  level: INFO
  handlers: [default]